leveling:
  exp-curve: 1.0
  max-exp: 80000
  max-level: 50
  pad-max-level: true
  exp-loss: 0
  pvp-exp-loss: 0
  max-party-size: 100
  party-exp-bonus: 2
  level-loss: false
  mastery-loss: false
  spawner-checks: true
  spawner-exp-mult: 0.5
  reset-on-death: false
  pvp-range: 1000
  min-pvp-level: 1
  pvp-exp-range: 10
  pvp-max-exp-range: 40
  dump-exp-file: false
classes:
  swap-cost: 0
  old-swap-cost: 0
  prof-swap-cost: 0
  old-prof-swap-cost: 0
  master-swap-free: true
  first-swap-free: true
  use-prefix: false
  reset-exp-on-change: true
  reset-master-on-change: false
  reset-prof-master-on-change: false
  reset-prof-on-pri-change: false
  lock-till-master: false
  lock-at-max-level: false
  self-heal: 0.5
  class-change-cooldown: 30
properties:
  storage-type: yml
  economy: false
  debug: false
  enchant-exp-mult: 0
  global-cooldown: 500
  block-tracking-duration: 900000
  max-tracked-blocks: 2000
  food-heal-percent: 0.05
  slow-while-casting: true
  combat-time: 30000
  reduce-item-damage: 4
  fix-legacy-health: true
bed:
  enabled: true
  interval: 15
  percent: 5
mana:
  interval: 10
  spout-mana-bar: true
bonus:
  expiration: 0
  exp: 1.0
  message: You have been granted bonus experience gains for a set time.
hats:
  level: 1
  enabled: true
worlds:
  disabled:
  - World1
  - World2
  - World3
